import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import supabase from '@/utils/supabase'
import { useEffect , useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data , setData] = useState([]);

  const fetchData = async () => {
    const {data , error} = await supabase.from("children").select()
    
    setData(data)
  }

  useEffect(() => {
    fetchData(); 
  },[]);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {data && data.map((item) => (
          <div key = {item.id}>
            <p className='text-white'>{item.title}</p>
            <img src={item.image} />
            <p>{item.intro}</p>
          </div>
        ))}
      </div>
    </>
  )
}
